### PR TITLE
Update to support OBS builds in same manner as cvmfs-contrib-release

### PR DESCRIPTION
**Pull request by tpdownes**
I have outwardly successful builds on all enabled platforms.

Would you consider enabling Ubuntu 18.04? I wish they had Debian testing/buster/10 as it's a common user platform. I realize these are not yet supported by CVMFS itself but they are useful for identifying problems and, eventually, CVMFS should be supporting these.

https://build.opensuse.org/package/show/home:tpdownes:branches:home:drdaved:cvmfs-contrib/cvmfs-setup-autofs

I believe that you'll have to delete the existing release and re-release. Since we're just playing around at this stage, I don't consider that to be a real issue. Going forward, of course, we'd have a real policy about fixing releases.

### CODE REVIEW

**Comment by DrDaveD** [comment]
Tom, so it already did have an obsupdate.sh and cvmfs-setup-autofs.dsc, I didn't notice before.  So part of what I said by email must have been confusing.

Could you please update this to change you to be the maintainer instead of me, and to increase the version number to 1.1-1?  It's also better to still have %{?dist} in the Release line; OBS overwrites to put that in anyway, but in case somebody else wants to also do an rpmbuild of the source rpm.

Sure I'll add Ubuntu 18.04.  So far I only added it to the contrib-testing repo for testing.

**Comment by tpdownes** [comment]
I think I've met the above requirements, but you've got about 5 different flavors of the `obsupdate.sh` script floating around and, frankly, I think I've fixed the debian description by breaking the redhat description to match the copy of the script I'm using.

It would help to standardize on a particular script and approach. NB: I made a change the regex search for `%define release_prefix` that makes it more friendly to aligning-whitespace.

**Comment by DrDaveD** [comment]
I don't really have a favorite.  Let me know if you've got a proposal for standardizing.

**Comment by tpdownes** [comment]
Well, the issue is that I don't know what correct output looks like for both deb/rpm files such that OBS produces the thing you want. I think I'd actually start from scratch and produce both files as the output of a script. I'd be happy to write that (someday soon-ish, but not next day or two) if you could identify two files that look right and tell me what deb/rpm filenames/versions they produced.

**Comment by DrDaveD** [comment]
All of the variants do produce working packages.  You can see the generated packages in the apt repo for example at https://download.opensuse.org/repositories/home:/cvmfs:/contrib/xUbuntu_18.04/all/ and coresponding yum repo at https://download.opensuse.org/repositories/home:/cvmfs:/contrib/CentOS_7/noarch/.  I think the cvmfs-contrib-release style is the most recent, but actually if the Debian release number could be for example 1.4-1 instead of 1.4.1 that would be better.  I am pretty sure I had some trouble with doing that but I can't remember the details; you could try doing it again.  I think there's a lot more variability in the format of Debian package version numbers than rpms.

I don't think it's a good idea to generate .spec files.  They are traditionally hand-edited and they work that way.  The .dsc file is the OBS-unique thing and I'd rather generate only that.

**Pull request closed without merging**
